---
- name: Run New Relic Installer
  shell: NR_INSTALL_SILENT=true newrelic-install install
  notify:
  - restart php-fpm
  - restart nginx

- name: restart php-fpm
  service: name=php5-fpm state=restarted

- name: restart nginx
  service: name=nginx state=restarted
